### ISSUE TITLE
Clone TellUsHowUCIT web site to Omeka demo instance

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/ops-requests#1]
## Description
Clone the entire [TellUsHowUCIt](https://library.ucsd.edu/tellushowucit/) production web site to the demo instance:

https://lib-omeka-demo.ucsd.edu/tellushowucit/

## Rationale
Tamara wants to play around and do testing with her website content without touching the production version.

**Comment by jhriv** [comment]
For reference: https://omeka.org/codex/Moving_to_Another_Server

**Comment by gamontoya** [comment]
Successfully cloned.
