### ISSUE TITLE
Update 404 page on YOURLS

### ISSUE THREAD

**Issue by JUMPquick** [ucsdlib/ops-requests#5]
Please update the 404 page on the YOURLS system to match the 404 page for the redesigned LPW.

Code attached.
[404page.txt](https://github.com/ucsdlib/ops-requests/files/1174036/404page.txt)

Note: URLs in the attached file are fully-qualified links, while the 404 page for LPW uses root-relative links.

**Comment by jhriv** [comment]
~Done.~

Apparently, it's not quite right and some links need updated even more.

**Comment by jhriv** [comment]
Done. For realsies this time
